-- Generated by _tools/build_letter_atlas.py — do not edit by hand.
-- Default red is fixed at #7e1011; modified is #16151a; black is fixed from legacy deck art.
return {
    red = { 0.494118, 0.062745, 0.066667, 1.0 },
    modified = { 0.086275, 0.082353, 0.101961, 1.0 },
    black = { 0.086275, 0.082353, 0.101961, 1.0 },
    gold = { 212 / 255, 175 / 255, 55 / 255, 1.0 },
}
