--[[
	Analyzer-only types for the live Game instance `G`.
	Not required by Love2D. LuaLS / EmmyLua pick this up via ---@meta.
]]

---@meta

---@class Transform
---@field x number
---@field y number
---@field w number
---@field h number
---@field r number
---@field scale number

---@class GameTimers
---@field TOTAL number
---@field REAL number
---@field UPTIME number
---@field BACKGROUND number

---@class CardCenter
---@field name string
---@field effect any
---@field set string
---@field config table
---@field order any
---@field cost number
---@field label string|nil
---@field consumeable any
---@field discovered boolean|nil
---@field eternal_compat boolean|nil

---@class CardAbility
---@field name string
---@field effect any
---@field set string
---@field extra table|nil
---@field extra_value number
---@field consumeable any
---@field bonus number
---@field h_size number
---@field d_size number
---@field couponed any
---@field [string] any

---@class AlphaState
---@field tokens number
---@field perks table
---@field perk_slots number
---@field stats table
---@field trade_used_this_hand boolean
---@field match_over boolean
---@field match_won boolean
---@field character_intro_active boolean|nil
---@field intro_waiting_score boolean|nil
---@field stage3_cinematic boolean|nil
---@field stage3_portrait_visible boolean|nil
---@field stage3_portrait_rect table|nil
---@field stage3_portrait_pose string|nil
---@field stage3_ally_portrait_rect table|nil
---@field stage3_guest_portrait_rect table|nil
---@field stage3_guest_pose string|nil
---@field [string] any

---@class JumbleState
---@field total_score number
---@field puzzle_index number
---@field solved boolean
---@field bonus_available boolean
---@field bonus_card_id any
---@field puzzle_points number
---@field puzzle_multi number
---@field puzzle_words string[]
---@field deadline number|nil
---@field time_left number|nil
---@field puzzle table|nil
---@field pattern string|nil
---@field slots table[]|nil
---@field [string] any

---@class WordRound
---@field set number
---@field hand_index number
---@field target number
---@field played_words string[]
---@field mode string|nil
---@field hand_name string|nil
---@field jumble JumbleState|nil
---@field [string] any

---@class GameRunState
---@field modifiers table
---@field round_resets table
---@field alpha AlphaState|nil
---@field won boolean|nil
---@field seeded boolean|nil
---@field pseudorandom table
---@field current_round table|nil
---@field round_scores any
---@field starting_deck_size number
---@field starting_params { hand_size: number, discards: number, hands: number, consumable_slots: number }
---@field word_round WordRound|nil
---@field placement_word string|nil
---@field placement_word_valid boolean|nil
---@field word_score_animating boolean|nil
---@field [string] any

---@class WordGameTableDeck
---@field uses_table_draw fun(): boolean
---@field draw fun(area: CardArea)
---@field show_info fun()

---@class WordGameCardInspect
---@field is fun(card: Card): boolean
---@field can_inspect fun(card: SceneNode): boolean
---@field begin_hold fun(card: SceneNode)

---@class WordGame
---@field Deck { reveal_in_hand: fun(card: Card), populate_jumble_deck: fun(), reset_table_deck: fun(), deal_jumble_hand: fun(), deal_into_hand: fun(n: number) }|nil
---@field TableDeck WordGameTableDeck|nil
---@field PlayerHost table|nil
---@field CardInspect WordGameCardInspect|nil
---@field Layout { sidebar_frac: fun(): number, sidebar_width: fun(): number, inner_width: fun(): number, update_all: fun(), request_refresh: fun() }|nil
---@field TableBoard { update: fun(game: Game, dt: number), draw_board: fun(game: Game), is_active: fun(): boolean }|nil

---@class GameInstanceTables
---@field NODE SceneNode[]
---@field MOVEABLE EaseNode[]
---@field SPRITE Sprite[]
---@field UIBOX UIPanel[]
---@field POPUP any[]
---@field CARD Card[]
---@field CARDAREA CardArea[]
---@field ALERT any[]

---@class GameThreadManager
---@field thread love.Thread
---@field channel love.Channel
---@field load_channel love.Channel|nil
---@field out_channel love.Channel|nil
---@field in_channel love.Channel|nil

---@class GameAtlasSpec
---@field name string
---@field path string
---@field px number
---@field py number
---@field frames number|nil
---@field cols number|nil
---@field rows number|nil
---@field type string|nil

---@class GameFontSpec
---@field file string
---@field render_scale number
---@field TEXT_HEIGHT_SCALE number
---@field TEXT_OFFSET {x: number, y: number}
---@field FONTSCALE number
---@field squish number
---@field DESCSCALE number
---@field FONT love.Font

---@class GameLanguage
---@field font GameFontSpec
---@field label string
---@field key string
---@field button string|nil
---@field warning string[]|nil
---@field beta boolean|nil
---@field omit boolean|nil

---@class (partial) Game : Class
---@field VERSION string
---@field STATE integer
---@field STAGE integer
---@field STATES table<string, integer>
---@field STAGES table<string, integer>
---@field STATE_COMPLETE boolean
---@field SETTINGS table
---@field F_RUMBLE any
---@field F_ENGLISH_ONLY boolean
---@field F_DISP_USERNAME any
---@field F_DISCORD boolean
---@field F_QUIT_BUTTON boolean
---@field F_NO_ACHIEVEMENTS boolean
---@field F_TROPHIES boolean
---@field F_PS4_PLAYSTATION_GLYPHS boolean
---@field F_EXTERNAL_LINKS boolean
---@field F_SWAP_AB_PIPS boolean
---@field focused_profile number
---@field save_settings fun(self: Game)
---@field C table
---@field UIT table
---@field FUNCS table
---@field ARGS table
---@field I GameInstanceTables
---@field TIMERS GameTimers
---@field FRAMES { DRAW: number, MOVE: number }
---@field GAME GameRunState
---@field ROOM SceneNode
---@field ROOM_ATTACH EaseNode
---@field hand CardArea|nil
---@field deck CardArea|nil
---@field discard CardArea|nil
---@field play CardArea|nil
---@field jokers CardArea|nil
---@field consumeables CardArea|nil
---@field view_deck CardArea[]|nil
---@field VIEWING_DECK any
---@field deck_preview any
---@field placement_table table|nil
---@field placement_table PlacementTable|nil
---@field real_dt number
---@field HIGHLIGHT_H number
---@field E_MANAGER Scheduler
---@field CONTROLLER InputController
---@field CURSOR Sprite
---@field MOVEABLES EaseNode[]
---@field DRAW_HASH SceneNode[]
---@field debug_panel DebugPanel|nil
---@field VIBRATION number
---@field P_CARDS table
---@field P_CENTERS table
---@field CARD_W number
---@field CARD_H number
---@field TILESIZE number
---@field TILESCALE number
---@field TILE_W number
---@field TILE_H number
---@field CANV_SCALE number
---@field SHADERS table<string, love.Shader>
---@field ASSET_ATLAS table
---@field ANIMATION_ATLAS table
---@field animation_atli GameAtlasSpec[]
---@field asset_atli GameAtlasSpec[]
---@field asset_images GameAtlasSpec[]
---@field ANIMATIONS table
---@field SPEEDFACTOR number
---@field shared_debuff Sprite
---@field shared_soul Sprite
---@field shared_undiscovered_joker Sprite
---@field shared_undiscovered_tarot Sprite
---@field shared_sticker_eternal Sprite
---@field shared_seals table<string, Sprite>
---@field ROOM_PADDING_H number
---@field ROOM_PADDING_W number
---@field WINDOWTRANS table
---@field window_prev table
---@field LANGUAGES table<string, GameLanguage>
---@field FONTS GameFontSpec[]
---@field BRUTE_OVERLAY table|nil
---@field HAND_CARD_SPACING number|nil
---@field TABLE_HAND_SIZE integer
---@field playing_cards Card[]|nil
---@field OVERLAY_MENU UIPanel|nil
---@field SHOW_SIDE_PANEL boolean
---@field check any
---@field LOADING any
---@field SPLASH_VOL number
---@field E_SWITCH_POINT number
---@field PROGRESS any
---@field DISCOVER_TALLIES any
---@field FILE_HANDLER any
---@field SAVED_GAME any
---@field action any
---@field culled_table any
---@field ROOM_ORIG any
---@field playing_card number
---@field muted boolean
---@field F_MUTE boolean
---@field F_ENABLE_PERF_OVERLAY boolean
---@field F_SOUND_THREAD boolean
---@field F_STREAMER_EVENT boolean
---@field F_VERBOSE boolean
---@field FPS_CAP number
---@field SEED number
---@field keybind_mapping any
---@field button_mapping table
---@field F_NO_ERROR_HAND boolean
---@field F_CRASH_REPORTS boolean
---@field buttons UIPanel|nil
---@field HUD UIPanel|nil
---@field CANVAS love.Canvas|nil
---@field update fun(self: Game, dt: number)
---@field draw fun(self: Game)
---@field STEAM LuaSteam|nil
---@field SOUND_MANAGER GameThreadManager|nil
---@field SAVE_MANAGER GameThreadManager
---@field PITCH_MOD number
---@field LANG GameLanguage
---@field localization table
---@field selected_back any
---@field PROFILES table
---@field start_up fun(self: Game)
---@field load_profile fun(self: Game, _profile: number)
---@field set_language fun(self: Game)
---@field set_render_settings fun(self: Game)
---@field init_window fun(self: Game, reset: boolean|nil)
---@field init_item_prototypes fun(self: Game)
---@field start_run fun(self: Game, args: table|nil)
---@field start_gameplay_board fun(self: Game)
---@field [string] any

---@type Game
G = {}

---@type WordGame
WORD_GAME = {}
