--[[
	types/game.lua - Live run state on G.GAME (analyzer-only).

	Runtime bus (live state stays on G):
	- **G.GAME** — authoritative run snapshot; domain modules read/write through their owner.
	- **G.FUNCS** — UI input callbacks by string name (catalog: types/g_funcs.lua).
	- **Presentation** — model→UI notify (contract: types/presentation.lua).

	Cross-package API:
	- **WORD_GAME** / **WORD_GAME_UI** facades are the supported entry points for app/, tests/,
	  and devtools. Prefer facade methods over new top-level G.GAME keys.
	- Do not guard UI with `WORD_GAME and WORD_GAME_UI.X` — after boot `WORD_GAME` is always
	  set; test the export: `if WORD_GAME_UI.X then …`. Use `WORD_GAME.Jumble` etc. for domain.

	Legacy naming (keep until save format bump):
	- `G.P_CENTERS` / `G.playing_cards` — inherited letter-card registry from the alpha engine.
	- `round_resets.ante` — set index (`word_round.set`); see `docs/gameplay.md`.

	Adding G.GAME fields:
	- Assign an owning module below and declare the field on GameRunState here.
	- Do not add ad-hoc keys from UI, tests, or one-off call sites without an owner.
	- UI animation gates either write a documented flag (see InputLock) or go through
	  run/busy.lua sync_from_ui for mirrored *_busy flags.
]]

---@meta

---@class Transform
---@field x number
---@field y number
---@field w number
---@field h number
---@field r number
---@field scale number

---@class GameTimers
---@field TOTAL number
---@field REAL number
---@field UPTIME number
---@field BACKGROUND number

---@class CardCenter
---@field name string
---@field effect any
---@field set string
---@field config table
---@field order any
---@field cost number
---@field label string|nil
---@field consumeable any
---@field discovered boolean|nil
---@field eternal_compat boolean|nil

---@class CardAbility
---@field name string
---@field effect any
---@field set string
---@field extra table|nil
---@field extra_value number
---@field consumeable any
---@field bonus number
---@field h_size number
---@field d_size number
---@field couponed any
---@field [string] any

---@class RunState
---@field tokens number
---@field perks table
---@field perk_slots number
---@field stats table
---@field trade_used_this_hand boolean
---@field match_over boolean
---@field match_won boolean
---@field [string] any

---@class JumbleSlot
---@field kind string
---@field letter string|nil
---@field cards table[]|nil
---@field min number|nil
---@field max number|nil

---@class JumbleState
---@field total_score number
---@field puzzle_index number|nil
---@field solved boolean
---@field bonus_available boolean|nil
---@field bonus_card_id string|nil
---@field puzzle_points number
---@field puzzle_multi number
---@field puzzle_words string[]
---@field puzzle table|nil
---@field pattern string|nil
---@field slots JumbleSlot[]|nil
---@field boss_word_active boolean|nil
---@field boss_word_staging boolean|nil
---@field boss_puzzle_hidden boolean|nil
---@field pending_boss table|nil
---@field boss_cards Card[]|nil
---@field locked_hand_layout table|nil

---@class WordRound
---@field set number
---@field hand_index number
---@field target number
---@field played_words string[]
---@field mode string|nil
---@field hand_name string|nil
---@field jumble JumbleState|nil
---@field [string] any

---@class GameRunState
--- Run-wide fields. Each group has a single owning module — extend here when adding keys.
---
--- Owner: model/game/run.lua, model/run/scope.lua
---@field run_mode "classic"|"time_run"|string|nil
---@field run_generation number|nil
---@field run_state RunState|nil
---@field won boolean|nil
---@field seeded boolean|nil
---@field pseudorandom table|nil
---@field seed_streams { seed: string, hashed_seed: number }|nil
---@field starting_deck_size number|nil
---@field starting_params { hand_size: number, usable_slots: number }|nil
---@field points number|nil
---@field round number|nil
---@field round_scores table<string, { amt: number }>|nil
--- Legacy save/results: `round_resets.ante` == `word_round.set` (set index; label kept for saves).
---@field round_resets { ante?: number, [string]: any }|nil
---@field modifiers table<string, boolean>|nil
---@field current_round table|nil
---@field deck_alpha { pos: { x: number, y: number } }|nil
---@field deck_left_count number|nil
---@field chips_text string|nil
---
--- Owner: model/round/init.lua (+ jumble/hand.lua for wr.jumble)
---@field word_round WordRound|nil
---
--- Owner: model/run/timeline.lua (Time Run fuse; classic goal/target reads)
---@field timeline_seconds number|nil
---@field timeline_duration number|nil
---@field timeline_active boolean|nil
---@field timeline_frozen boolean|nil
---@field timeline_boss_override boolean|nil
--- Owner: model/run/timeline.lua (fuse); classic mirror writes via ui/perks/timeline_timer
---@field timeline_goal_reached boolean|nil
---@field timeline_progress_target number|nil
---
--- Owner: model/jumble/placement_word.lua
---@field placement_word string|nil
---@field placement_word_valid boolean|nil
---
--- Owner: model/perks/voucher_discard.lua (+ round reset)
---@field voucher_discards_used number|nil
---@field discard_bin_count number|nil
---
--- Owner: model/perks/registry.lua
---@field selected_perk string|nil
---
--- Owner: model/jumble_play/* and ui/table/controls/* (InputLock reads)
---@field word_score_animating boolean|nil
---@field hand_shuffle_animating boolean|nil
---@field hand_redraw_animating boolean|nil
---@field placement_recall_animating boolean|nil
---
--- Owner: model/run/busy.lua (FX modules push on animation start/end)
---@field trade_ui_busy boolean|nil
---@field token_reward_busy boolean|nil
---@field card_fly_off_busy boolean|nil
---@field play_hold_redraw_busy boolean|nil
---@field [string] any

---@class WordGameTableDeck
---@field uses_table_draw fun(): boolean
---@field draw fun(area: CardArea)
---@field show_info fun()

---@class WordGameCardInspect
---@field is fun(card: Card): boolean
---@field can_inspect fun(card: SceneNode): boolean
---@field begin_hold fun(card: SceneNode)

---@class WordGameTableControls
---@field sync fun()
---@field sync_position fun()
---@field stabilize_table_board fun()
---@field shuffle_hand fun()
---@field placement_has_cards fun(): boolean
---@field destroy fun()|nil

---@class WordGamePlay
---@field on_hand_cleared fun(opts: table|nil)|nil
---@field continue_after_dealer fun()|nil
---@field resolve_after_clear fun(opts: table|nil): string
---@field jumble_next fun(opts: table|nil)|nil

---@class WordGame
---@field Deck table|nil
---@field Jumble table|nil
---@field Play WordGamePlay|nil
---@field TableControls WordGameTableControls|nil
---@field BonusStack table|nil
---@field BonusStackUI table|nil
---@field TableDeck WordGameTableDeck|nil
---@field TableInput { refresh_card_input: fun() }|nil
---@field CardInspect WordGameCardInspect|nil
---@field Layout { sidebar_frac: fun(): number, sidebar_width: fun(): number, inner_width: fun(): number, update_all: fun(), request_refresh: fun(), refresh_placement_layout: fun()|nil }|nil
---@field TableBoard { update: fun(game: Game, dt: number), draw_board: fun(game: Game), is_active: fun(): boolean }|nil
---@field Sidebar table|nil
---@field TradeUI table|nil
---@field ScoreBanner table|nil
---@field TimelineTimer table|nil
---@field TokenReward table|nil
---@field CardFlyOff table|nil
---@field InputLock table|nil

---@class GameInstanceTables
---@field NODE SceneNode[]
---@field MOVEABLE EaseNode[]
---@field SPRITE Sprite[]
---@field UIBOX UIPanel[]
---@field POPUP any[]
---@field CARD Card[]
---@field CARDAREA CardArea[]
---@field ALERT any[]

---@class GameThreadManager
---@field thread love.Thread
---@field channel love.Channel
---@field load_channel love.Channel|nil
---@field out_channel love.Channel|nil
---@field in_channel love.Channel|nil

---@class GameAtlasSpec
---@field name string
---@field path string
---@field px number
---@field py number
---@field frames number|nil
---@field cols number|nil
---@field rows number|nil
---@field type string|nil

---@class GameFontSpec
---@field file string
---@field render_scale number
---@field TEXT_HEIGHT_SCALE number
---@field TEXT_OFFSET {x: number, y: number}
---@field FONTSCALE number
---@field squish number
---@field DESCSCALE number
---@field FONT love.Font

---@class GameLanguage
---@field font GameFontSpec
---@field label string
---@field key string
---@field button string|nil
---@field warning string[]|nil
---@field beta boolean|nil
---@field omit boolean|nil

---@class (partial) Game : Class
---@field VERSION string
---@field STATE integer
---@field STAGE integer
---@field STATES table<string, integer>
---@field STAGES table<string, integer>
---@field STATE_COMPLETE boolean
---@field SETTINGS table
---@field F_RUMBLE any
---@field F_ENGLISH_ONLY boolean
---@field F_DISP_USERNAME any
---@field F_DISCORD boolean
---@field F_PS4_PLAYSTATION_GLYPHS boolean
---@field F_SWAP_AB_PIPS boolean
---@field focused_profile number
---@field save_settings fun(self: Game)
---@field C table
---@field UIT table
---@field FUNCS GameFuncs UI input bus — string names in types/g_funcs.lua
---@field ARGS table
---@field I GameInstanceTables
---@field TIMERS GameTimers
---@field FRAMES { DRAW: number, MOVE: number }
---@field GAME GameRunState Live run snapshot — field owners in types/game.lua
---@field ROOM SceneNode
---@field ROOM_ATTACH EaseNode
---@field hand CardArea|nil
---@field deck CardArea|nil
---@field discard CardArea|nil
---@field play CardArea|nil
---@field hand_action_bar UIPanel|nil
---@field table_shuffle_bar UIPanel|nil
---@field hand_play_button UIPanel|nil
---@field table_shuffle_button UIPanel|nil
---@field PLAY_WORD_UI UIPanel|nil
---@field SIDEBAR_HUD UIPanel|nil
---@field TIMELINE table|nil
---@field OVERLAY_MENU UIPanel|nil
---@field RUN { active: boolean }|nil
---@field consumeables CardArea|nil
---@field view_deck CardArea[]|nil
---@field VIEWING_DECK any
---@field deck_preview any
---@field placement_table table|nil
---@field placement_table PlacementTable|nil
---@field real_dt number
---@field HIGHLIGHT_H number
---@field E_MANAGER Scheduler
---@field CONTROLLER InputController
---@field CURSOR Sprite
---@field MOVEABLES EaseNode[]
---@field DRAW_HASH SceneNode[]
---@field debug_panel DebugPanel|nil
---@field VIBRATION number
---@field P_CARDS table
---@field P_CENTERS table Legacy letter-card center registry (rename deferred until save bump)
---@field CARD_W number
---@field CARD_H number
---@field TILESIZE number
---@field TILESCALE number
---@field TILE_W number
---@field TILE_H number
---@field CANV_SCALE number
---@field SHADERS table<string, love.Shader>
---@field ASSET_ATLAS table
---@field ANIMATION_ATLAS table
---@field animation_atli GameAtlasSpec[]
---@field asset_atli GameAtlasSpec[]
---@field asset_images GameAtlasSpec[]
---@field ANIMATIONS table
---@field SPEEDFACTOR number
---@field shared_debuff Sprite
---@field ROOM_PADDING_H number
---@field ROOM_PADDING_W number
---@field WINDOWTRANS table
---@field window_prev table
---@field LANGUAGES table<string, GameLanguage>
---@field FONTS GameFontSpec[]
---@field BRUTE_OVERLAY table|nil
---@field HAND_CARD_SPACING number|nil
---@field TABLE_HAND_SIZE integer
---@field playing_cards Card[]|nil Legacy live deck inventory (rename deferred until save bump)
---@field OVERLAY_MENU UIPanel|nil
---@field SHOW_SIDE_PANEL boolean
---@field check any
---@field LOADING any
---@field SPLASH_VOL number
---@field E_SWITCH_POINT number
---@field PROGRESS any
---@field DISCOVER_TALLIES any
---@field FILE_HANDLER any
---@field SAVED_GAME any
---@field action any
---@field culled_table any
---@field ROOM_ORIG any
---@field playing_card number
---@field muted boolean
---@field F_MUTE boolean
---@field F_ENABLE_PERF_OVERLAY boolean
---@field F_SOUND_THREAD boolean
---@field F_STREAMER_EVENT boolean
---@field F_VERBOSE boolean
---@field FPS_CAP number
---@field SEED number
---@field keybind_mapping any
---@field button_mapping table
---@field F_NO_ERROR_HAND boolean
---@field F_CRASH_REPORTS boolean
---@field buttons UIPanel|nil
---@field HUD UIPanel|nil
---@field CANVAS love.Canvas|nil
---@field update fun(self: Game, dt: number)
---@field draw fun(self: Game)
---@field STEAM LuaSteam|nil
---@field SOUND_MANAGER GameThreadManager|nil
---@field SAVE_MANAGER GameThreadManager
---@field PITCH_MOD number
---@field LANG GameLanguage
---@field localization table
---@field selected_back any
---@field PROFILES table
---@field start_up fun(self: Game)
---@field load_profile fun(self: Game, _profile: number)
---@field set_language fun(self: Game)
---@field set_render_settings fun(self: Game)
---@field init_window fun(self: Game, reset: boolean|nil)
---@field init_item_prototypes fun(self: Game)
---@field start_run fun(self: Game, args: table|nil)
---@field start_gameplay_board fun(self: Game)
---@field [string] any

---@type Game
G = {}

---@type WordGame
WORD_GAME = {}
