return {
["descriptions"]={},
["misc"]={
  ["dictionary"]={
    ["$"]="$",
    ["hdr_you_win"]="YOU WIN!",
    ["ui_copy"]="Copy",
    ["ui_start_new_run"]="New Run",
    ["ui_main_menu"]="Main Menu",
    ["hdr_demo_thanks_1"]="Thanks for playing the",
    ["hdr_demo_thanks_2"]="Jumbalaya Demo",
    ["hdr_game_over"]="GAME OVER",
    ["term_round"]="Round",
    ["term_seed"]="Seed",
    ["term_no_space_ex"]="No Space!",
    ["ui_seed"]="Seed",
    ["ui_settings"]="Settings",
    ["ui_classic"]="Classic",
    ["ui_time_run"]="Time Run",
    ["ui_set_game"]="Game",
    ["ui_set_video"]="Video",
    ["ui_set_graphics"]="Graphics",
    ["ui_set_audio"]="Audio",
    ["ui_set_gamespeed"]="Game Speed",
    ["ui_set_play_discard_pos"]="Play/Discard Button Position",
    ["ui_set_rumble"]="Controller Rumble",
    ["ui_set_screenshake"]="Screenshake",
    ["ui_high_contrast_cards"]="High Contrast Cards",
    ["ui_set_crash_reports"]="Crash Reports",
    ["opt_crash_report_info"]={
[1]="Opens a mail draft to support@jumbalaya.co",
[2]="with the crash log. You still choose whether",
[3]="to send it. Nothing is uploaded automatically.",
},
    ["ui_set_monitor"]="Display Monitor",
    ["ui_set_windowmode"]="Window Mode",
    ["ui_set_apply"]="Apply",
    ["ui_set_master_vol"]="Master Volume",
    ["ui_set_music_vol"]="Music Volume",
    ["ui_set_game_vol"]="Game Volume",
    ["ui_set_shadows"]="Shadows",
    ["ui_set_pixel_smoothing"]="Pixel Art Smoothing",
    ["term_perk"]="Voucher",
    ["term_deck"]="Deck",
    ["term_unlocked_ex"]="Unlocked!",
    ["term_common"]="Common",
    ["term_uncommon"]="Uncommon",
    ["term_rare"]="Rare",
    ["term_legendary"]="Legendary",
    ["term_debuffed"]="Debuffed",
    ["term_enter_name"]="Enter Name",
    ["term_empty_caps"]="EMPTY",
    ["term_wins"]="Wins",
    ["ui_current_profile"]="Current Profile",
    ["ui_load_profile"]="Load Profile",
    ["ui_create_profile"]="Create Profile",
    ["ui_reset_profile"]="Reset Profile",
    ["ui_delete_profile"]="Delete Profile",
    ["hdr_click_confirm"]="Click again to confirm",
    ["term_profile"]="Profile",
    ["term_playing_as"]="Playing as",
    ["ui_play_cap"]="PLAY",
    ["ui_options_cap"]="OPTIONS",
    ["ui_quit_cap"]="QUIT",
    ["ui_back"]="Back",
    ["term_enter_text"]="Enter Text",
    ["term_swapped_ex"]="Swapped!",
    ["hdr_score_hand"]="Best Hand",
    ["hdr_score_cards_discarded"]="Cards Discarded",
    ["hdr_score_seed"]="Seed",
    ["term_locked"]="Locked",
    ["term_undiscovered"]="Undiscovered",
    ["term_enhanced"]="Enhanced",
    ["term_default"]="Default",
    ["opt_play_discard_pos_opt"]={
[1]="Discard/Play",
[2]="Play/Discard",
},
    ["opt_windowmode_opt"]={
[1]="Windowed",
[2]="Fullscreen",
[3]="Borderless",
},
    ["opt_vsync_opt"]={
[1]="VSync On",
[2]="VSync Off",
},
    ["opt_shadow_opt"]={
[1]="On",
[2]="Off",
},
    ["opt_smoothing_opt"]={
[1]="Off",
[2]="On",
},
    ["opt_demo_thanks_message"]={
[1]="Thank you for playing",
[2]="the Jumbalaya demo!",
},
  },
  ["v_dictionary"]={
    ["a_chips"]="+#1#",
    ["a_mult"]="+#1# Mult",
    ["a_xmult"]="X#1# Mult",
  },
  ["tutorial"]={
    ["first_play_welcome"]={
[1]="Welcome to {C:attention}Jumbalaya{}!",
[2]="A strategic game of word puzzling!",
},
    ["first_play_hand"]={
[1]="You get dealt {C:attention}7{} random cards.",
[2]="All cards are worth {C:attention}1{} point.",
},
    ["first_play_placement"]={
[1]="This is where you play your cards.",
[2]="Every time you play on the same puzzle word your mult increases by {C:attention}0.2x{}.",
},
    ["first_play_positions"]={
[1]="The numbers underneath the fixed letters show the position.",
[2]="For example {C:attention}C{} will always be in position {C:attention}1{}.",
[3]="{C:attention}T{} will always be in the last position.",
},
    ["first_play_play_button"]={
[1]="You have to at least play {C:attention}1{} word on each puzzle word.",
[2]="To get a different puzzle word press {C:attention}Play{} again without any letters placed on the board.",
},
    ["first_play_goal"]={
[1]="Your goal is to get the target score as shown here.",
[2]="Good luck!",
},
    ["invalid_word"]={
[1]="{C:attention}#1#{} is not a valid word!",
},
  },
  ["quips"]={
    ["lq_1"]={
[1]="Maybe Go Fish",
[2]="is more our",
[3]="speed...",
},
  },
  ["high_scores"]={
    ["hand"]="Best Hand",
    ["furthest_round"]="Highest Round",
    ["furthest_set"]="Highest Set",
    ["most_points"]="Most Points",
    ["win_streak"]="Best Win Streak",
    ["current_streak"]="",
    ["boss_streak"]="Most Bosses in a Row",
    ["most_money"]="Most Money",
  },
  ["v_text"]={},
},
}
