return {
["descriptions"]={},
["misc"]={
  ["dictionary"]={
    ["$"]="$",
    ["hdr_you_win"]="YOU WIN!",
    ["ui_copy"]="Copy",
    ["ui_start_new_run"]="New Run",
    ["ui_main_menu"]="Main Menu",
    ["hdr_demo_thanks_1"]="Thanks for playing the",
    ["hdr_demo_thanks_2"]="Jumbalaya Demo",
    ["hdr_game_over"]="GAME OVER",
    ["term_round"]="Round",
    ["term_seed"]="Seed",
    ["term_no_space_ex"]="No Space!",
    ["ui_seed"]="Seed",
    ["ui_settings"]="Settings",
    ["ui_classic"]="Classic",
    ["ui_time_run"]="Time Run",
    ["ui_set_game"]="Game",
    ["ui_set_video"]="Video",
    ["ui_set_graphics"]="Graphics",
    ["ui_set_audio"]="Audio",
    ["ui_set_gamespeed"]="Game Speed",
    ["ui_set_play_discard_pos"]="Play/Discard Button Position",
    ["ui_set_rumble"]="Controller Rumble",
    ["ui_set_screenshake"]="Screenshake",
    ["ui_high_contrast_cards"]="High Contrast Cards",
    ["ui_set_crash_reports"]="Crash Reports",
    ["opt_crash_report_info"]={
[1]="Crash reports will be sent to the developer",
[2]="to help reduce issues in the future. No",
[3]="identifying or personal info will be sent.",
},
    ["ui_set_monitor"]="Display Monitor",
    ["ui_set_windowmode"]="Window Mode",
    ["ui_set_apply"]="Apply",
    ["ui_set_master_vol"]="Master Volume",
    ["ui_set_music_vol"]="Music Volume",
    ["ui_set_game_vol"]="Game Volume",
    ["ui_set_shadows"]="Shadows",
    ["ui_set_pixel_smoothing"]="Pixel Art Smoothing",
    ["term_perk"]="Voucher",
    ["term_deck"]="Deck",
    ["term_unlocked_ex"]="Unlocked!",
    ["term_common"]="Common",
    ["term_uncommon"]="Uncommon",
    ["term_rare"]="Rare",
    ["term_legendary"]="Legendary",
    ["term_debuffed"]="Debuffed",
    ["term_enter_name"]="Enter Name",
    ["term_empty_caps"]="EMPTY",
    ["term_wins"]="Wins",
    ["ui_current_profile"]="Current Profile",
    ["ui_load_profile"]="Load Profile",
    ["ui_create_profile"]="Create Profile",
    ["ui_reset_profile"]="Reset Profile",
    ["ui_delete_profile"]="Delete Profile",
    ["ui_unlock_all"]="Unlock All",
    ["term_trophies_disabled"]="Trophies Disabled",
    ["term_achievements_disabled"]="Achievements Disabled",
    ["hdr_click_confirm"]="Click again to confirm",
    ["term_profile"]="Profile",
    ["term_playing_as"]="Playing as",
    ["ui_play_cap"]="PLAY",
    ["ui_options_cap"]="OPTIONS",
    ["ui_quit_cap"]="QUIT",
    ["ui_back"]="Back",
    ["term_enter_text"]="Enter Text",
    ["term_swapped_ex"]="Swapped!",
    ["hdr_score_hand"]="Best Hand",
    ["hdr_score_cards_discarded"]="Cards Discarded",
    ["hdr_score_seed"]="Seed",
    ["term_locked"]="Locked",
    ["term_undiscovered"]="Undiscovered",
    ["term_enhanced"]="Enhanced",
    ["term_default"]="Default",
    ["opt_play_discard_pos_opt"]={
[1]="Discard/Play",
[2]="Play/Discard",
},
    ["opt_windowmode_opt"]={
[1]="Windowed",
[2]="Fullscreen",
[3]="Borderless",
},
    ["opt_vsync_opt"]={
[1]="VSync On",
[2]="VSync Off",
},
    ["opt_shadow_opt"]={
[1]="On",
[2]="Off",
},
    ["opt_smoothing_opt"]={
[1]="Off",
[2]="On",
},
    ["opt_demo_thanks_message"]={
[1]="Thank you for playing",
[2]="the Jumbalaya demo!",
},
  },
  ["v_dictionary"]={
    ["a_chips"]="+#1#",
    ["a_mult"]="+#1# Mult",
    ["a_xmult"]="X#1# Mult",
  },
  ["tutorial"]={
    ["sb_1"]={
[1]="Hi I'm {C:attention}Pads{}!",
[2]="Let's learn to play",
[3]="{C:attention}Jumbalaya{}!",
},
    ["milo_intro"]={
[1]="Hi, I'm Milo.",
[2]="Welcome to Jumbalaya!",
},
    ["milo_intro_hand"]={
[1]="Below is your hand.",
[2]="They will always contain letters and at least {C:attention}1 vowel{}!",
},
    ["milo_intro_play"]={
[1]="Play any standard word inside the card area.",
[2]="Do it now play {C:attention}KEY{}!",
},
    ["milo_intro_play_key"]={
[1]="Play the word {C:attention}KEY{} inside the card area",
[2]="like I told you!",
},
    ["milo_intro_goal"]={
[1]="Great! You scored {C:attention}10{} points!",
[2]="Get that down to {C:attention}0{}. Only {C:attention}2{} to go!",
},
    ["milo_intro_abilities"]={
[1]="Oh! By the way, I don't have any special abilities",
[2]="but maybe you might meet others that do!",
},
    ["milo_intro_goodluck"]={
[1]="Good luck!",
},
    ["milo_nice_work"]={
[1]="Nice work!",
},
    ["milo_stage3"]={
[1]="{C:attention}Boss Battle{}!",
[2]="Round {C:attention}3{} — this is the big one.",
},
    ["boss_stage3_intro"]={
[1]="This will be a tough battle.",
[2]="Are you ready?",
},
    ["aleisha_stage3_intro"]={
[1]="Hi! My name is {C:attention}Aleisha{}.",
[2]="I'm here to help you.",
},
    ["aleisha_stage3_ability"]={
[1]="I have special abilities!",
[2]="{C:red}Red{} is my favourite color.",
},
    ["aleisha_stage3_red"]={
[1]="Every {C:red}red{} letter scored is a {C:attention}+2{}.",
[2]="If the whole word is {C:red}red{}",
[3]="it will double your score!",
},
    ["aleisha_stage3_go"]={
[1]="You start though.",
[2]="Let's go!",
},
    ["boss_stage23_intro"]={
[1]="Another round. Another fight.",
[2]="Don't get comfortable.",
},
    ["marco_stage23_intro"]={
[1]="Hi! My name is {C:attention}Marco{}.",
[2]="I'm here to help you.",
},
    ["marco_stage23_go"]={
[1]="I'll stand with Aleisha.",
[2]="Let's go!",
},
    ["marco_stage23_ability"]={
[1]="Vowels are {C:attention}+3{} for me.",
[2]="We all inherit the bonuses of the player on our left.",
},
    ["invalid_word"]={
[1]="{C:attention}#1#{} is not a valid word!",
},
  },
  ["quips"]={
    ["lq_1"]={
[1]="Maybe Go Fish",
[2]="is more our",
[3]="speed...",
},
  },
  ["labels"]={
    ["foil"]="Foil",
    ["blue_seal"]="Blue Seal",
    ["rare"]="Rare",
    ["perk"]="Perk",
    ["purple_seal"]="Purple Seal",
    ["gold_seal"]="Gold Seal",
    ["red_seal"]="Red Seal",
    ["negative"]="Negative",
    ["common"]="Common",
    ["pinned_left"]="Pinned",
    ["legendary"]="Legendary",
    ["eternal"]="Eternal",
    ["holographic"]="Holographic",
    ["uncommon"]="Uncommon",
    ["locked"]="Locked",
    ["polychrome"]="Polychrome",
    ["negative_consumable"]="Negative",
  },
  ["high_scores"]={
    ["hand"]="Best Hand",
    ["furthest_round"]="Highest Round",
    ["furthest_set"]="Highest Set",
    ["most_points"]="Most Points",
    ["win_streak"]="Best Win Streak",
    ["current_streak"]="",
    ["furthest_ante"]="Highest Ante",
    ["boss_streak"]="Most Bosses in a Row",
    ["most_money"]="Most Money",
  },
  ["v_text"]={},
  ["achievement_names"]={},
},
}
