--[[ tests/unit/test_marketplace_compositing.lua - Marketplace overlay contract ]]

local T = require("tests.framework")

T.describe("marketplace overlay", function()
	T.it("paints the marketplace modal after table chrome and before the pointer", function()
		local paths = require("bootstrap_paths").resolve()
		local file = io.open(paths.game_root .. "/app/session/draw_passes.lua", "r")
			or io.open(paths.game_root .. "/games/jumbalaya/app/session/draw_passes.lua", "r")
		T.assert_not_nil(file)
		local src = file:read("*a")
		file:close()
		local modal_pos = src:find("draw_modal_on_top")
		local pointer_pos = src:find("game.POINTER:draw")
		T.assert_not_nil(modal_pos)
		T.assert_not_nil(pointer_pos)
		T.assert_true(modal_pos < pointer_pos, "marketplace should cover table chrome but leave the cursor on top")
	end)

	T.it("skips the table board pass while the marketplace is open", function()
		local paths = require("bootstrap_paths").resolve()
		local file = io.open(paths.game_root .. "/app/session/draw_passes.lua", "r")
			or io.open(paths.game_root .. "/games/jumbalaya/app/session/draw_passes.lua", "r")
		T.assert_not_nil(file)
		local src = file:read("*a")
		file:close()
		T.assert_true(src:find("trade_marketplace_open"), "board pass should gate on marketplace open")
		T.assert_true(src:find("not trade_marketplace_open"), "table chrome should not paint under the modal")
	end)

	T.it("lays out draw-layer marketplace overlays inside the stage box", function()
		local paths = require("bootstrap_paths").resolve()
		local file = io.open(paths.path_under_repo("packages", "jumbalaya-engine", "panels", "panel_layout.lua"), "r")
		T.assert_not_nil(file)
		local src = file:read("*a")
		file:close()
		T.assert_true(src:find("draw_layer"), "panel layout should special-case draw_layer overlays")
	end)

	T.it("registers marketplace action callbacks", function()
		require("word_game.ui.callbacks.trade")
		local Funcs = require("app.callbacks.funcs")
		T.assert_not_nil(Funcs.get("trade_close"))
		T.assert_not_nil(Funcs.get("trade_market_add"))
		T.assert_not_nil(Funcs.get("trade_market_remove"))
		T.assert_not_nil(Funcs.get("trade_market_modify"))
	end)
end)
