--[[ tests/unit/test_game_access.lua - Store-backed game snapshot access ]]

local T = require("tests.framework")
local mock_env = require("tests.helpers.mock_env")
local Store = require("jumbalaya_core.store")
local Engine = require("jumbalaya-engine")
local store_ops = require("word_game.model.store_ops")
local game_access = require("word_game.model.game_access")
local word_game = require("word_game")
local runtime = require("app.runtime")

T.describe("game_access and store authority", function()
	mock_env.reset_game()

	T.it("binds store and engine on WORD_GAME, not G", function()
		T.assert_not_nil(word_game.store())
		T.assert_not_nil(word_game.engine())
		T.assert_nil(G._store)
		T.assert_nil(G._engine)
		T.assert_equal(runtime.store(), word_game.store())
		T.assert_equal(runtime.engine(), word_game.engine())
	end)

	T.it("reads and patches via store only", function()
		local store = Store.new({ points = 42, round = 1 })
		word_game._bind_store(store)
		store_ops.bind_run(store, store:get())
		T.assert_equal(game_access.get().points, 42)
		game_access.patch({ round = 3 })
		T.assert_equal(store:get().round, 3)
		T.assert_equal(game_access.get().round, 3)
		mock_env.reset_game()
	end)

	T.it("dispatch updates store snapshot", function()
		game_access.dispatch({ type = "SHUFFLE_HAND" })
		T.assert_equal(word_game.store():get().shuffle_hand_count, 1)
		T.assert_equal(game_access.get().shuffle_hand_count, 1)
	end)

	T.it("allows tests to bind an isolated store via WORD_GAME", function()
		local store = Store.new({ points = 99 })
		word_game._bind_store(store)
		T.assert_equal(word_game.store():get().points, 99)
		T.assert_nil(G._store)
	end)

	T.it("allows tests to bind engine context via WORD_GAME", function()
		local store = Store.new()
		local engine = Engine.Context.new({ store = store })
		word_game._bind_engine(engine)
		T.assert_equal(runtime.engine(), engine)
		T.assert_nil(G._engine)
	end)

	T.it("mutate notifies store subscribers", function()
		mock_env.reset_game()
		local store = Store.new({ round = 1 })
		word_game._bind_store(store)
		store_ops.bind_run(store, store:get())
		local seen_round = nil
		local function on_state(state)
			seen_round = state.round
		end
		store:subscribe(on_state)
		game_access.mutate(function(g)
			g.round = 2
		end)
		store:unsubscribe(on_state)
		T.assert_equal(seen_round, 2)
		T.assert_equal(store:get().round, 2)
	end)
end)
