--[[ tests/unit/test_input_lock.lua - Shared gameplay input gates ]]

local T = require("tests.framework")
local mock_env = require("tests.helpers.mock_env")
local InputLock = require("word_game.model.run.input_lock")
local BonusStack = require("word_game.model.jumble.bonus_stack")
local Busy = require("word_game.model.run.busy")

T.describe("InputLock.is_table_busy", function()
	T.it("blocks while bonus gutter cards are animating", function()
		mock_env.reset_game()
		BonusStack.clear()
		T.assert_false(InputLock.is_table_busy())
		BonusStack.set_animating(true)
		T.assert_true(InputLock.is_table_busy())
		BonusStack.set_animating(false)
		T.assert_false(InputLock.is_table_busy())
	end)

	T.it("blocks while trade marketplace card is flying", function()
		mock_env.reset_game()
		Busy.set("trade_ui_busy", true)
		T.assert_true(InputLock.is_table_busy())
		Busy.set("trade_ui_busy", false)
		T.assert_false(InputLock.is_table_busy())
	end)

	T.it("blocks while trade marketplace transform is running", function()
		mock_env.reset_game()
		Busy.set("trade_ui_busy", true)
		T.assert_true(InputLock.is_table_busy())
	end)

	T.it("blocks while token reward flyers are active", function()
		mock_env.reset_game()
		Busy.set("token_reward_busy", true)
		T.assert_true(InputLock.is_table_busy())
		Busy.set("token_reward_busy", false)
		T.assert_false(InputLock.is_table_busy())
	end)

	T.it("blocks while played cards are flying off", function()
		mock_env.reset_game()
		Busy.set("card_fly_off_busy", true)
		T.assert_true(InputLock.is_table_busy())
		Busy.set("card_fly_off_busy", false)
		T.assert_false(InputLock.is_table_busy())
	end)
end)
