--[[ tests/unit/test_phase7_store_authority.lua - Phase 7 store/engine owned by WORD_GAME ]]

local T = require("tests.framework")
local mock_env = require("tests.helpers.mock_env")
local Store = require("jumbalaya_core.store")
local Engine = require("jumbalaya-engine")
local word_game = require("word_game")
local runtime = require("app.runtime")

T.describe("Phase 7 Store Authority", function()
	mock_env.reset_game()

	T.it("binds store and engine on WORD_GAME, not G", function()
		T.assert_not_nil(word_game.store())
		T.assert_not_nil(word_game.engine())
		T.assert_nil(G._store)
		T.assert_nil(G._engine)
		T.assert_equal(runtime.store(), word_game.store())
		T.assert_equal(runtime.engine(), word_game.engine())
	end)

	T.it("game_access reads state from WORD_GAME.store", function()
		local game_access = require("word_game.model.game_access")
		word_game.Round.init_run()
		T.assert_equal(game_access.get(), word_game.state())
	end)

	T.it("dispatch updates store snapshot", function()
		local game_access = require("word_game.model.game_access")
		game_access.dispatch({ type = "SHUFFLE_HAND" })
		T.assert_equal(word_game.store():get().shuffle_hand_count, 1)
		T.assert_equal(game_access.get().shuffle_hand_count, 1)
	end)

	T.it("allows tests to bind an isolated store via WORD_GAME", function()
		local store = Store.new({ points = 99 })
		word_game._bind_store(store)
		T.assert_equal(word_game.store():get().points, 99)
		T.assert_nil(G._store)
	end)

	T.it("allows tests to bind engine context via WORD_GAME", function()
		local store = Store.new()
		local engine = Engine.Context.new({ store = store })
		word_game._bind_engine(engine)
		T.assert_equal(runtime.engine(), engine)
		T.assert_nil(G._engine)
	end)
end)
